services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: edusynthDb
      POSTGRES_USER: edusynthDb
      POSTGRES_PASSWORD: edusynthDb
    ports:
      - "5432:5432"
    networks:
      - edusynth_net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: orlikov.andrei@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: orlikov.andrei@yandex.ru
    ports:
      - "5050:80"
    networks:
      - edusynth_net
    depends_on:
      - postgres

  redis:
    image: redis:6.2-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - edusynth_net

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: rabbitmq-container
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: edusynth
      RABBITMQ_DEFAULT_PASS: edusynth123
      RABBITMQ_DEFAULT_VHOST: /edusynth
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - edusynth_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  edusynth_net:
    driver: bridge